
[auth0]
client_id = "YOUR_AUTH0_CLIENT_ID"
client_secret = "YOUR_AUTH0_CLIENT_SECRET"
domain = "YOUR_DOMAIN.auth0.com"

[supabase]
url = "https://your-project.supabase.co"
key = "your-service-role-key"
bucket = "uploads"
